// AI Sprint Planner - API Test Suite (Node.js)
const URL = 'http://localhost:3000/v1/plans';
const DESC = 'The MGROC-style grocery e-commerce backend provides a complete platform for managing grocery products, customers, orders, payments, delivery, administration, content, and business operations.';
const FULL = ['Project scaffold','Database layer','Authentication core','OTP service','Auth middleware','Security hardening','Request validation','i18n','Logging','API envelope','File service','Master data','Product management','Product catalog','App version gating','Customer accounts','Address book','Wishlist','Cart','Checkout','Pricing engine','Payment status','GST invoices','Admin Panel','ACL','Admin user management','Delivery-agent','Reports','Order management','Banner management','CMS content','Deep links','SEO management','Transactional emails','Queue integration','Social login','Lead management','Expense management','Multi-language translations','Warehouse readiness','Order edge cases'];
const SMALL = ['Project scaffold','Database layer','Authentication core','OTP service','Cart','Checkout','Customer accounts','Admin user management'];
const BASE = { description: DESC, project_name: 'Mgroc demo 1', project_id: '6aa3dcab151ea1909a177bd9', start_date: '2026-09-13' };

async function post(body) {
  const res = await fetch(URL, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  return res.json();
}

function extract(d) {
  // Navigate the nested response structure
  const dataset = d.response && d.response.dataset ? d.response.dataset : null;
  if (!dataset) return { error: 'No dataset in response', raw: JSON.stringify(d).slice(0,300) };
  const plan = dataset.plan || {};
  const input = dataset.input || {};
  const sprints = plan.sprints || [];
  const teamBreakdown = input.team_breakdown || {};
  const teamSize = Object.values(teamBreakdown).reduce(function(a,b){return a+b;},0);
  return {
    planName: plan.plan_name,
    summary: plan.summary,
    totalWeeks: plan.total_duration_weeks || 0,
    sprints: sprints,
    teamSize: teamSize,
    teamBreakdown: teamBreakdown,
    featuresCount: (input.features || []).length,
    lastSprintDeadline: sprints.length > 0 ? sprints[sprints.length-1].deadline : null,
    model: dataset.model,
    generatedBy: dataset.generated_by
  };
}

function show(label, d) {
  console.log('\n' + '='.repeat(60));
  console.log('TEST: ' + label);
  console.log('='.repeat(60));
  const info = extract(d);
  if (info.error) { console.log('ERROR: ' + info.error); console.log(info.raw); return; }
  console.log('  Model: ' + info.model + ' | Generated by: ' + info.generatedBy);
  console.log('  Plan: ' + info.planName);
  console.log('  Summary: ' + info.summary);
  console.log('  Team size: ' + info.teamSize + ' ' + JSON.stringify(info.teamBreakdown));
  console.log('  Features sent: ' + info.featuresCount);
  console.log('  Sprints: ' + info.sprints.length + ' | Total weeks: ' + info.totalWeeks);
  console.log('  Last sprint deadline: ' + info.lastSprintDeadline);
  info.sprints.forEach(function(s,i) {
    console.log('    S'+(i+1)+': "'+(s.name||'?')+'" | tasks:'+(s.tasks||[]).length+' | pts:'+(s.planned_points||'?')+' | '+s.start_date+' -> '+s.end_date);
  });
}

async function main() {
  var t1 = await post(Object.assign({}, BASE, { team_breakdown: { ui: 2, backend: 3, app: 2, others: 1 }, features: FULL }));
  show('Team Size INCREASE (3 -> 8 members)', t1);

  var t2 = await post(Object.assign({}, BASE, { team_breakdown: { backend: 1 }, features: FULL }));
  show('Team Size DECREASE (3 -> 1 member)', t2);

  var t3 = await post(Object.assign({}, BASE, { team_breakdown: { ui: 1, backend: 1, app: 1 }, features: SMALL }));
  show('FEWER Features (40 -> 8 features)', t3);

  var t4 = await post(Object.assign({}, BASE, { team_breakdown: { ui: 1, backend: 1, app: 1 }, deadline: '2026-12-31', rules: 'Feature implementing sprint should have features name wise mile stone', features: FULL }));
  show('Rules + Deadline Impact (deadline 2026-12-31)', t4);

  var t5 = await post(Object.assign({}, BASE, { team_breakdown: { ui: 1, backend: 1, app: 1 }, sprint_length_weeks: 2, rules: 'Each sprint must be feature-wise and include milestone names', features: SMALL }));
  show('Logical Request Structure (8 features, 2wk sprints)', t5);

  console.log('\n' + '='.repeat(60));
  console.log('COMPARISON SUMMARY');
  console.log('='.repeat(60));
  function row(name, info) {
    var deadlineCheck = info.lastSprintDeadline ? info.lastSprintDeadline : 'N/A';
    console.log(name.padEnd(18) +
      'Sprints:' + String(info.sprints.length).padStart(3) +
      ' | Weeks:' + String(info.totalWeeks).padStart(3) +
      ' | Team:' + String(info.teamSize).padStart(2) +
      ' | Feats:' + String(info.featuresCount).padStart(2) +
      ' | Ends:' + deadlineCheck);
  }
  row('Test1 (team 8):', extract(t1));
  row('Test2 (team 1):', extract(t2));
  row('Test3 (feat 8):', extract(t3));
  row('Test4 (rules+DL):', extract(t4));
  row('Test5 (logical):', extract(t5));

  console.log('\n' + '='.repeat(60));
  console.log('ANALYSIS');
  console.log('='.repeat(60));
  var e1 = extract(t1), e2 = extract(t2), e3 = extract(t3), e4 = extract(t4), e5 = extract(t5);
  console.log('[Test 1 vs Test 2] Team size impact:');
  console.log('  Team 8 -> ' + e1.sprints.length + ' sprints, ' + e1.totalWeeks + ' weeks');
  console.log('  Team 1 -> ' + e2.sprints.length + ' sprints, ' + e2.totalWeeks + ' weeks');
  console.log('  => More team members should generally reduce sprints/weeks');

  console.log('\n[Test 1 vs Test 3] Feature count impact:');
  console.log('  40 features -> ' + e1.sprints.length + ' sprints, ' + e1.totalWeeks + ' weeks');
  console.log('  8 features  -> ' + e3.sprints.length + ' sprints, ' + e3.totalWeeks + ' weeks');
  console.log('  => Fewer features should reduce sprints/weeks');

  console.log('\n[Test 4] Rules + Deadline (2026-12-31):');
  console.log('  Ends: ' + e4.lastSprintDeadline);
  console.log('  => Sprint ends before deadline? ' + (e4.lastSprintDeadline && e4.lastSprintDeadline <= '2026-12-31' ? 'YES' : 'CHECK'));

  console.log('\n[Test 5] Feature-wise sprint division check:');
  console.log('  Sprints: ' + e5.sprints.length + ' (one per feature ideally = 8)');
  console.log('  2wk sprint length requested');
}

main().catch(function(e){ console.error('FATAL: ' + e.message); process.exit(1); });
